version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - aws s3 cp s3://s3-bucket-luna-charles-p1/app.properties ./src/main/resources/app.properties
  build:
    commands:
      - echo Build started on `date`
      - mvn package
      - mv target/*.war ./luna_charles_api_p1.war
  post_build:
    commands:
      - echo Build completed on `date`
      - unzip luna_charles_api_p1.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
      - ls
artifacts:
  files:
    - WEB-INF/**/*
  name: artifact
